---

- name: Copy binary
  copy:
    src: "{{bitsongcli_BINARY}}"
    dest: /usr/bin/bitsongcli
    mode: 0755
  notify: restart bitsongcli

- name: Copy service
  template:
    src: bitsongcli.service.j2
    dest: /etc/systemd/system/bitsongcli.service
  notify: systemctl

