---

- name: Fetch genesis.json
  fetch: "src=/home/bitsongd/.bitsongd/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: bitsongd

- name: Fetch config.toml
  fetch: "src=/home/bitsongd/.bitsongd/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: bitsongd

