init_config:

instances:
- name: ssh
  search_string: ['ssh', 'sshd']
  thresholds:
    critical: [1, 5]
- name: bitsongd
  search_string: ['bitsongd']
  thresholds:
    critical: [1, 1]
- name: bitsongcli
  search_string: ['bitsongcli']
  thresholds:
    critical: [1, 1]
